# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e248373eb781dcb7a15ebd4e1d2e959a707fbc05ad5c40f470f0872b9095e3cda630d85689257455df750e1820e97692515426eb428a20ba9d3fdf3e9eaaa006

test:
  secret_key_base: 22cbad1069eebb72aea006668cdcdee9e37c802b64a3b461e84a860d7581adbf193713461930f79e32177c0b780e2d06c394e28b66dba8ffe18bffcb03ac2bba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
